# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/sauna-api/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.AspNetCore.*"
        versions: ["9.x"]
      - dependency-name: "Swashbuckle.AspNetCore"
        versions: [ "9.x" ]
    groups:
      api-dependabot-nuget:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/sauna-sim-core/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      core-dependabot-nuget:
        applies-to: version-updates
        patterns:
          - "*"
      
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/sauna-tests/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.AspNetCore.*"
        versions: [ "9.x"]
      - dependency-name: "Swashbuckle.AspNetCore"
        versions: [ "9.x" ]
      - dependency-name: "NUnit"
        versions: [ "4.x" ]
      - dependency-name: "NUnit.*"
        versions: [ "4.x" ]
    groups:
      tests-dependabot-nuget:
        applies-to: version-updates
        patterns:
          - "*"
